### ISSUE TITLE
Not able to use multi-segment path in context path

### ISSUE THREAD

**Issue by lkq** [3redronin/mu-server#12]
With below context setup, requests to /api/fruits/xxx are not able to be routed to the handler

.addHandler(context("/api/fruits")
                        .addHandler(urlHandlerV1))

seems ContextHandler is storing a url encoded path for matching: "api%2Ffruits"
please confirm if this is an issue, I'm more than happy to provide a fix, or if it's not expected to use multi-segment path in context path, it should show some warning in the log. This bugged me for some time.

**Comment by danielflower** [comment]
Yes you are right, this looks like a bug.

**Comment by danielflower** [comment]
Thanks. Fixed in `0.15.4`
