### ISSUE TITLE
Filter by IP on RequestFilter?

### ISSUE THREAD

**Issue by lawkai** [3redronin/mu-server#14]
Using muserver 0.45.1, there is no way that we can access the remoteAddress property from muRequest via ContainerRequestContext. 
Sounds logical that this property should be exposed so that we can filter by ip?

**Comment by danielflower** [comment]
As I'm sure you saw, `ContainerRequestContext` is a jax-rs class that I can't change. There is a workaround you can use from version `0.46.0` though, now that the attributes on the [MuRequest](https://www.javadoc.io/doc/io.muserver/mu-server/latest/io/muserver/MuRequest.html) object share the same map as the ContainerRequestContext properties. So you can set the Mu Request object as an attribute on a handler before your rest handler, and then access it from a filter:

````java
public class FilterExample {

    public static void main(String[] args) {

        MuServer server = MuServerBuilder.httpsServer()
            .addHandler((request, response) -> {
                request.attribute("request", request);
                return false;
            })
            .addHandler(RestHandlerBuilder.restHandler()
                .addRequestFilter(requestContext -> {
                    MuRequest request = (MuRequest) requestContext.getProperty("request");
                    System.out.println("IP address is " + request.remoteAddress());
                })
                .addResource(new Blah())
            )
            .start();
        System.out.println("Started at " + server.uri().resolve("/blah"));
    }

    @Path("/blah")
    static class Blah {
        @GET
        public void blah() {}
    }
}
````

**Comment by lawkai** [comment]
Thanks, that would work.
