### ISSUE TITLE
Allow handlers to look at and manipulate headers without stopping the chain

### ISSUE THREAD

**Issue by michaeldeluna** [3redronin/mu-server#2]
Examples:
* Log all requests
* Add CORS headers to all responses
* Do security checks

**Comment by danielflower** [comment]
I think this works now. But is lacking a test... there is a HeadersTest class now which is where it could go.

There should also be tests for massive request headers... like can it handle a header value which is 32kb?

**Comment by danielflower** [comment]
Tested in https://github.com/3redronin/mu-server/commit/deb53a8ca314b9fbac64d408b346278190ad7177#diff-c2ca186eb5e61ae983efcbf37211c986R45
