### ISSUE TITLE
Handlers implementing interfaces with default methods

### ISSUE THREAD

**Issue by arundudani** [3redronin/mu-server#36]
I have encountered an issue with MuServer startup if there are any controllers which implement an interface with default methods.
During startup MuServer throws a NPE in such a case.

**In MuServerCode:**
Class: `io.muserver.rest.JaxMethodLocator`
Method: `static Method getMethodThatHasJaxRSAnnotations(Method start) `
Error Construct: `for(clazz = start.getDeclaringClass(); clazz != Object.class; clazz = clazz.getSuperclass())`

**Javadoc for getSuperClass() states that:** 
_Returns the Class representing the direct superclass of the entity (class, interface, primitive type or void) represented by this Class. If this Class represents either the Object class, an interface, a primitive type, or void, then null is returned. If this object represents an array class then the Class object representing the Object class is returned._

So in case Controller implements an interface with default methods, when that method is being processed by Annotations finder; getSuperclass() returns null and MuServer ends up throwing NPE.

**Comment by danielflower** [comment]
Thanks for the bug report. I reproduced in a unit test which I hope covers the case you described. Released in `0.72.5` - please reopen with more detail if you still have issues.
